[package]
name = "my-rust-actix"
version = "0.1.0"
authors = ["Dmitry Ishmaev <idax@rampbler.ru>"]
edition = "2018"

[dependencies]
actix-web = "2"
actix-rt = "1"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
futures-await-test = "0.3"
fake_clock = { version = "0.3.*" }
